---
  type: default # 'default' or 'dynamic'
  version: 1.5.0 # change every time this file is updated
  icons:
    icon_blacklist: ["ðŸ¦"] 
    system_icon: "ðŸ¦"
  ads:
  prices:
    tier_one:
        week:
          cost: 7
          id: null
        month:
          cost: 20
          id: null
        three_months:
          cost: 40
          id: null
    tier_two:
        week:
          cost: 10
          id: null
        month:
          cost: 30
          id: null
        three_months:
          cost: 60
          id: null
    tier_three:
        week:
          cost: 15
          id: null
        month:
          cost: 45
          id: null
        three_months:
          cost: 90
          id: null
  donation:
    prices:
      - cost: 5
        once: null # key for one-time price
        monthly: null # key for monthly price
      - cost: 10
        once: null
        monthly: null
      - cost: 20
        once: null
        monthly: null
      - cost: 50
        once: null
        monthly: null
      - cost: 100
        once: null
        monthly: null
    funding:
      - name: Hosting
        cost: 100
        markdown: >
          This is how much it costs to physically run the site.
      - name: Funding Goal 2
        cost: 200
        markdown: >
          Random thing.
      - name: Funding Goal 3
        cost: 600
        markdown: >
          Another thing that needs funding.
    goals:
      - name: Subscriber Perks
        cost: 400
        markdown: |
          We'll add on-site benefits to sponsors, account-holders with recurring donations, that will not impact the directory meta-game(We will explicitly not give sponsors reduced bump timers, post timers, or prompt priority). 
      - name: Extra Themes
        cost: 500
        markdown: |
          The site will have semi-customizable themes, including but not limited to options for site-layout(background, header, post, and text) colors and chat-list(unread, ended, answered) colors.
      - name: Archive Checkbox
        cost: 600
        markdown: |
          A checkbox will be placed in the Chat Info screen which, when every participant of a chat has it checked, will allow the chat to be viewable by non participants.
      - name: Site Statistics
        cost: 680
        markdown: |
          You'll have access to a monthly post containing curated data regarding the popularity of fandoms, various tags, and other assorted site statistics.
      - name: Push Notifications
        cost: 720
        markdown: |
          You'll have the option to enable notifications to be sent to your device or browser when you've got new unread replies, regardless of whether you're currently on the site or not.
      - name: Logical Blacklisting
        cost: 850
        markdown: |
          The blacklist will be upgraded with logical operators and priority setting, allowing for combinations (i.e. - if this tag is present, allow this other tag to be shown. Otherwise, hide it) so that you can have more control than a tag either showing or not.
      - name: Desktop App
        cost: 1100
        markdown: |
          We'll give creating a desktop client a go. If that doesn't work out - CherpBot on Discord.
      - name: Mobile App
        cost: 1500
        markdown: |
          We'll give creating a mobile(except for Apple devices) client a go.
  use:
    pages:
      index: 
        markdown: |+ # generic details on a page, rendered through redcarpet
          **Last updated: 1/5/2022**
          
          This is the ***index*** page.
        entries: # jsonable entries. Items are displayed in a list on the respective use page if this is set.
          - "See the **sidebar** for other, more useful pages."
          - "Note the **last updated** date at the top of each page."
      rules:
        markdown: |+
          **Last updated: 1/5/2022**

          **Crime and Punishment**

          This site operates on a tiered punishment system, with more serious offences or repeat violations earning a harsher punishment. The punishment tiers are as follows:
          
          - Tier 1 - Warning
          - Tier 2 - 1 Day Ban
          - Tier 3 - (Up to) 7 Day Ban
          - Tier 4 - Account Permaban
          - Tier 5 - IP Ban
          - Tier 6 - IP info turned over to authorities. Reserved for explicit illegal activities OOC.
        entries: 
          - Be kind. Tier 1.
          - Be mindful. Tier 1.
          - Be patient. Tier 1.
        titles:
          - Kindness
          - Mindfulness
          - Patience
      formatting:
        markdown: |+
          **Last updated: 1/5/2022**
          
          Among other things, you can *italicize* words like `*this*`. 
      tagging:
        markdown: |+
          **Last updated: 1/5/2022**
          
          Some tags in the Directory will be automatically wrangled.
      faq:
        markdown: |+
          **Last updated: 1/5/2022**
        entries:
          - |+ 
            What is this?

            An rp site.